global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "secure-data-pipeline-api"
    static_configs:
      - targets: ["host.docker.internal:5001"]
    metrics_path: "/api/metrics"
    scrape_interval: 15s
    scrape_timeout: 5s
    params:
      api_key: ["prometheus_key_2024"]

  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]
    scrape_interval: 30s

  - job_name: "pushgateway"
    static_configs:
      - targets: ["pushgateway:9091"]
    scrape_interval: 15s
    honor_labels: true
